// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlntimxtormpqgtcjcka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsbnRpbXh0b3JtcHFndGNqY2thIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzIyODYsImV4cCI6MjA2NDUwODI4Nn0.A8La0DefSoKIHR9lzmoAUP69YPqOldgShpM3tzmoLmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);